services:
  db:
    image: postgres:15
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
  app:
    build: .
    volumes:
      - .:/code
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - HERTZ_CHECK_INTERVAL=${HERTZ_CHECK_INTERVAL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - PUSHOVER_USER=${PUSHOVER_USER}
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    ports:
      - "${APP_PORT:-8000}:8000"
      - "${APP_DEBUGPY_PORT:-5678}:5678"
    depends_on:
      - db
      - redis
  worker:
    build: .
    entrypoint: ["/code/entrypoint-worker.sh"]
    volumes:
      - .:/code
    ports:
      - "5679:5678"  # Celery worker debugpy (host:container)
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - HERTZ_CHECK_INTERVAL=${HERTZ_CHECK_INTERVAL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  beat:
    build: .
    entrypoint: ["/code/entrypoint-beat.sh"]
    volumes:
      - .:/code
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - HERTZ_CHECK_INTERVAL=${HERTZ_CHECK_INTERVAL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
