# Generated by Django 5.2.5 on 2025-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifiedride',
            name='available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifiedride',
            name='car_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifiedride',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifiedride',
            name='latest_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifiedride',
            name='pickup_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifiedride',
            name='return_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifiedride',
            name='travel_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
